name: Build Docker image
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/pgils/docker-jetson-flash
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      if: ${{ startsWith( github.ref, 'refs/tags' ) }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push to GitHub Packages
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: ${{ startsWith( github.ref, 'refs/tags' ) }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
