name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag_action
      uses: anothrNick/github-tag-action@1.52.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        WITH_V: true
        RELEASE_BRANCHES: main

    - name: Set version in script
    # Update the first occurence of VERSION
      run: >
        sed -ie
        '0,/VERSION=/{s/VERSION=.*/VERSION=${{ steps.tag_action.outputs.tag }}/}'
        djetson-flash

    - name: Commit version update
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update VERSION'
        add: 'djetson-flash --force'
        tag: '${{ steps.tag_action.outputs.tag }} --force'
        tag_push: '--force'
