# all-in-one workflow since tags pushed with 'secrets.GITHUB_TOKEN'
# do not trigger other workflows (on.push.tags).
# https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/4

name: Bump and Build
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: pgils/docker-jetson-flash
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: pgils/docker-jetson-flash
        push: true
        tags: ${{ steps.prepare.outputs.tag }}
