on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
    - name: Run Hadolint
      uses: brpaz/hadolint-action@v1.4.0
      with:
        dockerfile: docker/Dockerfile
