on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
       version: v0.9.0
    - name: Run Hadolint
      uses: brpaz/hadolint-action@v1.5.0
      with:
        dockerfile: docker/Dockerfile
