name: Lint

on:
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v4
    -
      name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
       version: v0.9.0
    -
      name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/Dockerfile
